# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    #- uses: actions/checkout@v2
    - uses: benauca/action-git@develop
      with:
        repository: https://github.com/benauca/helloworld-execution-action.git
        #repository: ${{github.repository}}

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    
    # Run Docker ...
    - name: Start env
      run: docker version
    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
    - name: Run Docker image.
      run: docker run docker.pkg.github.com/benauca/hello-world-docker/hello-world:develop
    - name: Hello world action step
      id: hello
      uses: benauca/helloworld-action@develop
      with:
        username: ${{ github.actor }}
        password: "${{ secrets.GITHUB_TOKEN }}"
        who-to-greet: 'benauca'
            
